name: keras2circom
channels:
  - defaults
  - conda-forge
dependencies:
  - _ipython_minor_entry_point=8.7.0=h8cf3c4a_0
  - absl-py=1.3.0=py39hca03da5_0
  - aiohttp=3.8.3=py39h80987f9_0
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - appnope=0.1.3=pyhd8ed1ab_0
  - asttokens=2.2.1=pyhd8ed1ab_0
  - astunparse=1.6.3=py_0
  - async-timeout=4.0.2=py39hca03da5_0
  - attrs=22.1.0=py39hca03da5_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=pyhd8ed1ab_3
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - blas=1.0=openblas
  - blinker=1.4=py39hca03da5_0
  - brotli=1.0.9=h1a28f6b_7
  - brotli-bin=1.0.9=h1a28f6b_7
  - brotlipy=0.7.0=py39h1a28f6b_1002
  - bzip2=1.0.8=h620ffc9_4
  - c-ares=1.18.1=h1a28f6b_0
  - ca-certificates=2022.10.11=hca03da5_0
  - cachetools=4.2.2=pyhd3eb1b0_0
  - certifi=2022.9.24=py39hca03da5_0
  - cffi=1.15.1=py39h80987f9_3
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.0.4=py39hca03da5_0
  - comm=0.1.2=pyhd8ed1ab_0
  - contourpy=1.0.5=py39h525c30c_0
  - cryptography=38.0.1=py39h834c97f_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - dataclasses=0.8=pyh6d0b6a4_7
  - debugpy=1.6.4=py39h23fbdae_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - docopt=0.6.2=py39hca03da5_1
  - entrypoints=0.4=pyhd8ed1ab_0
  - executing=1.2.0=pyhd8ed1ab_0
  - flatbuffers=2.0.0=hc377ac9_0
  - flit-core=3.6.0=pyhd3eb1b0_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.11.0=h1192e45_0
  - frozenlist=1.3.3=py39h80987f9_0
  - gast=0.4.0=pyhd3eb1b0_0
  - giflib=5.2.1=h1a28f6b_0
  - google-auth=2.6.0=pyhd3eb1b0_0
  - google-auth-oauthlib=0.4.4=pyhd3eb1b0_0
  - google-pasta=0.2.0=pyhd3eb1b0_0
  - grpc-cpp=1.47.1=h503f348_6
  - grpcio=1.47.1=py39h13431ec_6
  - h5py=3.7.0=py39h7fe8675_0
  - hdf5=1.12.1=h160e8cb_2
  - icu=70.1=h6b3803e_0
  - idna=3.4=py39hca03da5_0
  - importlib-metadata=4.11.3=py39hca03da5_0
  - ipykernel=6.19.2=pyh736e0ef_0
  - ipython=8.7.0=pyhd1c38e8_0
  - jedi=0.18.2=pyhd8ed1ab_0
  - jpeg=9e=h1a28f6b_0
  - jupyter_client=7.4.8=pyhd8ed1ab_0
  - jupyter_core=5.1.0=py39h2804cbe_0
  - keras=2.10.0=pyhd8ed1ab_0
  - keras-preprocessing=1.1.2=pyhd3eb1b0_0
  - kiwisolver=1.4.2=py39hc377ac9_0
  - krb5=1.19.2=h3b8d789_0
  - lcms2=2.12=hba8e193_0
  - lerc=3.0=hc377ac9_0
  - libabseil=20220623.0=cxx17_h28b99d4_6
  - libblas=3.9.0=16_osxarm64_openblas
  - libbrotlicommon=1.0.9=h1a28f6b_7
  - libbrotlidec=1.0.9=h1a28f6b_7
  - libbrotlienc=1.0.9=h1a28f6b_7
  - libcblas=3.9.0=16_osxarm64_openblas
  - libcurl=7.84.0=hc6d1d07_0
  - libcxx=14.0.6=h848a8c0_0
  - libdeflate=1.8=h1a28f6b_5
  - libedit=3.1.20210910=h1a28f6b_0
  - libev=4.33=h1a28f6b_1
  - libffi=3.4.2=hca03da5_6
  - libgfortran=5.0.0=11_3_0_hca03da5_28
  - libgfortran5=11.3.0=h009349e_28
  - liblapack=3.9.0=16_osxarm64_openblas
  - libnghttp2=1.46.0=h95c9599_0
  - libopenblas=0.3.21=h269037a_0
  - libpng=1.6.38=h76d750c_0
  - libprotobuf=3.21.7=hb5ab8b9_0
  - libsodium=1.0.18=h27ca646_1
  - libsqlite=3.39.4=h76d750c_0
  - libssh2=1.10.0=hf27765b_0
  - libtiff=4.4.0=had003b8_0
  - libwebp=1.2.4=h68602c7_0
  - libwebp-base=1.2.4=h1a28f6b_0
  - libzlib=1.2.12=h03a7124_3
  - llvm-openmp=14.0.6=hc6e5704_0
  - lz4-c=1.9.4=h313beb8_0
  - markdown=3.3.4=py39hca03da5_0
  - matplotlib=3.6.2=py39hca03da5_0
  - matplotlib-base=3.6.2=py39h8bbb115_0
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - multidict=6.0.2=py39h1a28f6b_0
  - munkres=1.1.4=py_0
  - ncurses=6.3=h1a28f6b_3
  - nest-asyncio=1.5.6=pyhd8ed1ab_0
  - nomkl=3.0=0
  - numpy=1.23.4=py39h1398885_0
  - numpy-base=1.23.4=py39h90707a3_0
  - oauthlib=3.2.1=py39hca03da5_0
  - openblas=0.3.21=hca03da5_0
  - openblas-devel=0.3.21=hca03da5_0
  - openssl=1.1.1s=h1a28f6b_0
  - opt_einsum=3.3.0=pyhd3eb1b0_1
  - packaging=21.3=pyhd3eb1b0_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pexpect=4.8.0=pyh1a96a4e_2
  - pickleshare=0.7.5=py_1003
  - pillow=9.2.0=py39h4d1bdd5_1
  - pip=22.3.1=py39hca03da5_0
  - pipreqs=0.4.11=pyhd8ed1ab_0
  - platformdirs=2.6.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.36=pyha770c72_0
  - protobuf=4.21.7=py39h23fbdae_0
  - psutil=5.9.4=py39h02fc5c5_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pyasn1=0.4.8=pyhd3eb1b0_0
  - pyasn1-modules=0.2.8=py_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.13.0=pyhd8ed1ab_0
  - pyjwt=2.4.0=py39hca03da5_0
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pyparsing=3.0.9=py39hca03da5_0
  - pysocks=1.7.1=py39hca03da5_0
  - python=3.9.13=hc596b02_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-flatbuffers=2.0=pyhd3eb1b0_0
  - python_abi=3.9=3_cp39
  - pyzmq=24.0.1=py39h0553236_1
  - re2=2022.06.01=h9a09cb3_1
  - readline=8.2=h1a28f6b_0
  - requests=2.28.1=py39hca03da5_0
  - requests-oauthlib=1.3.0=py_0
  - rsa=4.7.2=pyhd3eb1b0_1
  - scipy=1.9.3=py39h18313fe_2
  - setuptools=65.5.0=py39hca03da5_0
  - six=1.16.0=pyhd3eb1b0_1
  - snappy=1.1.9=hc377ac9_0
  - sqlite=3.39.3=h1058600_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - tensorboard=2.10.1=pyhd8ed1ab_0
  - tensorboard-data-server=0.6.1=py39haa0b8cc_4
  - tensorboard-plugin-wit=1.6.0=py_0
  - tensorflow=2.10.0=cpu_py39h2839aeb_0
  - tensorflow-base=2.10.0=cpu_py39h0d4f425_0
  - tensorflow-estimator=2.10.0=cpu_py39h63f9d84_0
  - termcolor=2.1.0=py39hca03da5_0
  - tk=8.6.12=hb8d0fd4_0
  - tornado=6.2=py39h02fc5c5_1
  - traitlets=5.7.1=pyhd8ed1ab_0
  - typing_extensions=4.4.0=py39hca03da5_0
  - tzdata=2022g=h04d1e81_0
  - urllib3=1.26.13=py39hca03da5_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - werkzeug=2.0.3=pyhd3eb1b0_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - wrapt=1.14.1=py39h1a28f6b_0
  - xz=5.2.8=h80987f9_0
  - yarg=0.1.9=py_1
  - yarl=1.8.1=py39h1a28f6b_0
  - zeromq=4.3.4=hbdafb3b_1
  - zipp=3.8.0=py39hca03da5_0
  - zlib=1.2.12=h5a0b063_3
  - zstd=1.5.2=h8574219_0
prefix: ~/keras2circom
